# Generated by Django 5.2.3 on 2025-12-11 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parliament_number', models.IntegerField(blank=True, null=True)),
                ('meeting_number', models.IntegerField(blank=True, null=True)),
                ('sitting_date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('pdf_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hansardfile')),
            ],
        ),
    ]
