# Generated by Django 5.2.3 on 2025-12-11 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_debatesegment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hansardfile',
            options={'ordering': ['-date_downloaded']},
        ),
    ]
