# Generated by Django 5.2.3 on 2025-12-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_speaker_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='debatesegment',
            name='word_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
