# Generated by Django 5.2.3 on 2025-12-13 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_debatesegment_word_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('session', 'Full Session'), ('topic', 'Topic Discussion'), ('segment', 'Single Segment'), ('custom', 'Custom Text')], default='custom', max_length=20)),
                ('original_text', models.TextField()),
                ('summary_text', models.TextField()),
                ('speakers_mentioned', models.JSONField(blank=True, default=list, help_text='List of speakers mentioned')),
                ('motions', models.JSONField(blank=True, default=list, help_text='List of motions discussed')),
                ('outcomes', models.JSONField(blank=True, default=list, help_text='List of outcomes/decisions')),
                ('original_word_count', models.IntegerField()),
                ('summary_word_count', models.IntegerField()),
                ('reduction_percentage', models.FloatField(default=0)),
                ('created_by', models.CharField(default='system', help_text='User who requested the summary', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debate_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='app.debatesegment')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='app.session')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='app.topic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]

