# Generated by Django 6.0.4 on 2026-05-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParliamentaryLeadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='leadership/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Parliamentary Leadership',
                'ordering': ['order'],
            },
        ),
    ]
