# Generated by Django 6.0.4 on 2026-05-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_parliamentaryleadership'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parliamentaryleadership',
            options={'verbose_name_plural': 'Parliamentary Leadership'},
        ),
        migrations.RemoveField(
            model_name='parliamentaryleadership',
            name='description',
        ),
        migrations.RemoveField(
            model_name='parliamentaryleadership',
            name='name',
        ),
        migrations.RemoveField(
            model_name='parliamentaryleadership',
            name='order',
        ),
        migrations.RemoveField(
            model_name='parliamentaryleadership',
            name='title',
        ),
        migrations.AlterField(
            model_name='parliamentaryleadership',
            name='role',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
