# Generated by Django 6.0.4 on 2026-05-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_parliamentaryleadership_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='constituency',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='party',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='role',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
