# Generated by Django 5.2.9 on 2026-06-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_speaker_constituency_speaker_party_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='action_items',
            field=models.JSONField(blank=True, default=list, help_text='List of identified action items'),
        ),
        migrations.AddField(
            model_name='summary',
            name='debate_timeline',
            field=models.JSONField(blank=True, default=list, help_text='Sequence of events for visualization'),
        ),
        migrations.AddField(
            model_name='summary',
            name='sentiment_data',
            field=models.JSONField(blank=True, default=dict, help_text='Sentiment analysis scores'),
        ),
        migrations.AddField(
            model_name='summary',
            name='speaker_stats',
            field=models.JSONField(blank=True, default=dict, help_text='Word count and time distribution'),
        ),
    ]
